using System;
using System.Text;

public class NameGenerator
{
    string[] titles;
    string[] firstNames;
    string[] middleNames;
    string[] nickNames;
    string[] lastNames;

    public string GenerateCoolCopName(int seed)
    {
        StringBuilder nameBuilder = new StringBuilder();
        Random random = new Random(seed);

        if (random.Next(0, 10) > 6)
            nameBuilder.Append(titles[random.Next(0, titles.Length - 1)] + " ");

        nameBuilder.Append(firstNames[random.Next(0, firstNames.Length - 1)]);

        if (random.Next(0, 200) > 199)
            nameBuilder.Append("-chan");

        nameBuilder.Append(" ");

        if (random.Next(0, 10) > 8)
            nameBuilder.Append(middleNames[random.Next(0, middleNames.Length - 1)] + " ");


        if (random.Next(0, 10) > 8)
            nameBuilder.Append(nickNames[random.Next(0, nickNames.Length - 1)] + " ");

        nameBuilder.Append(lastNames[random.Next(0, lastNames.Length - 1)]);

        return nameBuilder.ToString();
    }

    public NameGenerator()
    {
        titles = new string[]
        {
        "Sgt.",
        "Lt.",
        "Cpl.",
        "LCpl.",
        "Major",
        "Captain",
        "Officer",
        "Detective",
        "The Honorable",
        "Sir",
        "Righteous",
        "Constable",
        "Justicar",
        "Magistrate",
        "Inquisitor",
        "Grenadier",
        "Commandant",
        "Légionnaire",
        "Commissar",
        "Brigadier"
        };

        firstNames = new string[]
        {
        "John",
        "Jason",
        "Gordon",
        "Tallahassee",
        "Baptiste",
        "Mathis",
        "Andrej",
        "Vinny",
        "Judge",
        "Dick",
        "Duncan",
        "Jeremiah",
        "Chad",
        "Brad",
        "Lewis",
        "Joe",
        "Morgan",
        "Logan",
        "Jimmy",
        "Moe",
        "Lester",
        "Otis",
        "Franz",
        "Hans",
        "Atticus",
        "Remmington",
        "Omaha",
        "Langston",
        "Hank",
        "Channing",
        "Dave",
        "Brick",
        "Driscoll",
        "Devon",
        "Dash",
        "Rodrigo",
        "Chaz",
        "Paul",
        "Maddox",
        "Kentucky",
        "Hug",
        "Frank",
        "Dietrich",
        "Scott",
        "Vito",
        "Domenik",
        "Omar",
        "Magnus",
        "Gabe",
        "Clutch",
        "Beaumont",
        "Simon",
        "Hamil",
        "Sebastian",
        "Owl",
        "Peregrin",
        "Cave",
        "Donald",
        "Ringo",
        "Bilbo",
        "Damascus",
        "Thomas",
        "Harry",
        "Sherlock",
        "Guilliam",
        "Lance",
        "Micky",
        "Bob",
        "Ronnie",
        "Niles",
        "Clive",
        "Chester",
        "DeForrest",
        "Horatio",
        "Malcolm",
        "Leonard",
        "Larry",
        "Steve",
        "Robert",
        "Marco",
        "Jason",
        "Nolan",
        "Sergei",
        "Ned",
        "Jeremy",
        "Roland",
        "Bertram",
        "Fernando",
        "Kevin",
        "Chuck",
        "Ryan",
        "Harlow",
        "Adolfo",
        "Victor",
        "Werner",
        "Cartwright",
        "Jeff",
        "Otto",
        "Wolf",
        "Tomahawk",
        "D'Angelo",
        "Esperanza",
        "Leslie",
        "Dimitri",
        "Sasha",
        "Alex",
        "Igor",
        "Ginger",
        "Udo"
        };

        middleNames = new string[]
        {
        "A.",
        "B.",
        "C.",
        "D.",
        "E.",
        "F.",
        "G.",
        "H.",
        "I.",
        "J.",
        "K.",
        "L.",
        "M.",
        "N.",
         "O.",
            "P.",
            "Q.",
            "R.",
            "S.",
            "U.",
            "V.",
            "W.",
            "X.",
            "Y.",
            "Z.",
            "van der",
            "van",
            "von"
            };

        nickNames = new string[]
        {
            "'Messiah'",
            "'Grinder'",
            "'Justice'",
            "'Demon'",
            "'The Bull'",
            "'The Machine'",
            "'Sisyphos'",
            "'Two Times'",
            "'Beast'",
            "'Merchandise'",
            "'Motorcycle'",
            "'Gigabyte'",
            "'Shatterdome'",
            "'Uwu'",
            "'Sensei'",
            "'Prime'",
            "'Game'",
            "'Harddrive'",
            "'God'",
            "'Ohio'",
            "'Viking'",
            "'Valhall'",
            "'Valhall'",
            "'Cleanser'",
            "'The Smartest Boy Alive'",
            "'Demigod'",
            "'The Hunt'",
            "'Sun King'",
            "'Emperor'"
        };

        lastNames = new string[]
        {
            "Jones",
            "Bach",
            "Greenseth",
            "Coldager",
            "Waller",
            "Bearman",
            "Thompson",
            "Swanson",
            "Steele",
            "Irons",
            "Hancock",
            "Cock",
            "Waters",
            "Lester",
            "Hardick",
            "Christmas",
            "Berger",
            "Utsi",
            "Ass",
            "Pringles",
            "King",
            "Thunderknife",
            "Nightblade",
            "Marlborough",
            "Navarro",
            "Gallipoli",
            "Mayweather",
            "Bloodharvest",
            "Slash",
            "Van Dijk",
            "Reagan",
            "Sharp",
            "Shark",
            "Maulman",
            "Djanque",
            "Price",
            "Bukkake",
            "Sudoku",
            "Truthchurch",
            "Breach",
            "Ocean",
            "II",
            "III",
            "IV",
            "V",
            "VI",
            "VII",
            "Haliburton",
            "Blackwater",
            "Crimejustice",
            "Loosecannon",
            "Swahili",
            "Cruise",
            "Hutt",
            "Hammer",
            "O'Driscoll",
            "Engels",
            "Johnson",
            "Eckhart",
            "Sullivan",
            "Palace",
            "Champion",
            "Wong",
            "Buttertable",
            "Yakamora",
            "Seagull",
            "Taintchucker",
            "Lunt",
            "Dimaggio",
            "Bundy",
            "Oswald",
            "Aids",
            "Fairbanks",
            "Hirohito",
            "Niceman",
            "Dukemageddon",
            "Ducca",
            "Cigarette",
            "Proudcreek",
            "Orenblatt",
            "Thickfeather",
            "Meancloud",
            "Redeagle",
            "Fuck",
            "Meganslaw",
            "Clevertaint",
            "Angrybear",
            "Wahlberg",
            "Depression",
            "Juncker",
            "Junker",
            "Bismarck",
            "Hindenburg",
            "Chestnut",
            "Stable",
            "Float",
            "Workswellwithothers",
            "Shows-Potential",
            "Helpful",
            "Scar",
            "Firestorm"
        };
    }
}
